In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
Liver_df = pd.read_csv('indian_liver_patient.csv')
Liver_df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [6]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
Liver_df['Gender'] = l.fit_transform(Liver_df['Gender'])
Liver_df.head(10)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   
5   46       1              1.8               0.7                   208   
6   26       0              0.9               0.2                   154   
7   29       0              0.9               0.3                   202   
8   17       1              0.9               0.3                   202   
9   55       1              0.7               0.2                   290   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   
5                        19                          14             7.6   
6                        16                          12             7.0   
7                        14                          11             6.7   
8                        22                          19             7.4   
9                        53                          58             6.8   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1  
5      4.4                        1.30        1  
6      3.5                        1.00        1  
7      3.6                        1.10        1  
8      4.1                        1.20        2  
9      3.4                        1.00        1

In [7]:
Liver_df.Albumin_and_Globulin_Ratio = Liver_df.Albumin_and_Globulin_Ratio.fillna(Liver_df['Albumin_and_Globulin_Ratio'].mean())
Liver_df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [8]:
corr_matrix = Liver_df.corr()
corr_matrix['Dataset']*100

Age                           -13.735063
Gender                         -8.241591
Total_Bilirubin               -22.020756
Direct_Bilirubin              -24.604634
Alkaline_Phosphotase          -18.486561
Alamine_Aminotransferase      -16.341616
Aspartate_Aminotransferase    -15.193375
Total_Protiens                  3.500824
Albumin                        16.138782
Albumin_and_Globulin_Ratio     16.231913
Dataset                       100.000000
Name: Dataset, dtype: float64

In [10]:
X =  Liver_df.drop(['Dataset','Total_Protiens','Alamine_Aminotransferase','Total_Protiens','Direct_Bilirubin','Total_Bilirubin'], axis=1)
y = Liver_df['Dataset']
X

Age  Gender  Alkaline_Phosphotase  Aspartate_Aminotransferase  Albumin  \
0     65       0                   187                          18      3.3   
1     62       1                   699                         100      3.2   
2     62       1                   490                          68      3.3   
3     58       1                   182                          20      3.4   
4     72       1                   195                          59      2.4   
..   ...     ...                   ...                         ...      ...   
578   60       1                   500                          34      1.6   
579   40       1                    98                          31      3.2   
580   52       1                   245                          49      3.2   
581   31       1                   184                          32      3.4   
582   38       1                   216                          24      4.4   

     Albumin_and_Globulin_Ratio  
0                          0.90  
1                          0.74  
2                          0.89  
3                          1.00  
4                          0.40  
..                          ...  
578                        0.37  
579                        1.10  
580                        1.00  
581                        1.00  
582                        1.50  

[583 rows x 6 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test =train_test_split(X,y,test_size=0.2, random_state=1)
print(X_train.shape, X_test.shape)
X_train.shape[0]+ X_test.shape[0]

(466, 6) (117, 6)


583

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [13]:
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)
print(X_train_sc)
print("----------------------")
print(X_test_sc)

[[ 0.06316812  0.56909018 -0.32679549 -0.40865992  1.57860838  1.0553238 ]
 [ 1.16933548  0.56909018 -0.57819903 -0.36205765  0.05477305  1.33343006]
 [ 0.49334431 -1.75719074 -0.31881443 -0.32477583  0.94367699 -0.18070403]
 ...
 [ 1.84532664 -1.75719074 -0.33876709 -0.36205765 -1.46906228 -0.48971099]
 [ 0.92352051  0.56909018  0.27976544  0.91484459 -1.46906228 -0.48971099]
 [ 0.06316812 -1.75719074  0.33563289 -0.11506561 -1.46906228 -0.48971099]]
----------------------
[[-4.28461821e-01  5.69090183e-01  2.27104112e+00 -2.50212196e-01
  -1.99199504e-01  1.28302926e-01]
 [-2.02625912e+00  5.69090183e-01  4.83145578e-02 -1.61667880e-01
   4.35731882e-01  4.37309884e-01]
 [ 7.39159282e-01  5.69090183e-01  7.18724005e-01 -6.38031100e-02
  -8.34130889e-01 -4.89710988e-01]
 [ 1.86075602e-01  5.69090183e-01 -1.31259401e-01  6.66832504e-02
  -1.21508972e+00 -1.04592351e+00]
 [-3.05554337e-01  5.69090183e-01  2.71784373e-01 -1.24386063e-01
  -1.34207600e+00 -1.41673186e+00]
 [ 6.31681171e-0

In [17]:
X_train_sc = pd.DataFrame(X_train_sc, columns=["Age","Gender","Alkaline_Phosphotase","Aspartate_Aminotransferase","Albumin","Albumin_and_Globulin_Ratio"])
X_test_sc = pd.DataFrame(X_test_sc, columns=["Age","Gender","Alkaline_Phosphotase","Aspartate_Aminotransferase","Albumin","Albumin_and_Globulin_Ratio"])
X_train_sc.describe().round()

Age  Gender  Alkaline_Phosphotase  Aspartate_Aminotransferase  \
count  466.0   466.0                 466.0                       466.0   
mean    -0.0    -0.0                   0.0                         0.0   
std      1.0     1.0                   1.0                         1.0   
min     -3.0    -2.0                  -1.0                        -0.0   
25%     -1.0     1.0                  -0.0                        -0.0   
50%      0.0     1.0                  -0.0                        -0.0   
75%      1.0     1.0                   0.0                        -0.0   
max      3.0     1.0                   7.0                        13.0   

       Albumin  Albumin_and_Globulin_Ratio  
count    466.0                       466.0  
mean      -0.0                         0.0  
std        1.0                         1.0  
min       -3.0                        -2.0  
25%       -1.0                        -1.0  
50%       -0.0                        -0.0  
75%        1.0                         0.0  
max        3.0                         6.0

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
scores = cross_val_score(DecisionTreeClassifier(),X,y, cv=5)
scores

array([0.56410256, 0.63247863, 0.66666667, 0.5862069 , 0.70689655])

In [21]:
scores.mean()*100

63.127026230474506

In [22]:
from sklearn.ensemble import BaggingClassifier
bag_model = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0    
)
bag_model.fit(X_train_sc,y_train)
bag_model.oob_score_*100 #68.24

C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


68.24034334763948

In [23]:
bag_model.score(X_test_sc,y_test)*100 # 67

67.52136752136752

In [24]:
bag_model = BaggingClassifier(
    base_estimator = DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0    
)

scores = cross_val_score(bag_model,X,y, cv=5)
scores.mean()*100 # 68.78573533745947

C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
C:\Users\babun\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` 

68.78573533745947

In [25]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(), X,y,cv=5)
scores.mean()*100 # 69.8113763631005

69.8113763631005